import type { Metadata } from "next";
import { ToastContainer } from 'react-toastify';
import "./globals.css";

export const metadata: Metadata = {
  title: "Project-management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        {children}
        <ToastContainer/>
      </body>
    </html>
  );
}
